apiVersion: v1
kind: Service
metadata:
  name: despachos-backend
  namespace: innovatech-chile
spec:
  selector:
    app: despachos-backend
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
