apiVersion: apps/v1
kind: Deployment
metadata:
  name: despachos-backend
  namespace: innovatech-chile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: despachos-backend
  template:
    metadata:
      labels:
        app: despachos-backend
      annotations:
        instrumentation.opentelemetry.io/inject-java: "false"
        instrumentation.opentelemetry.io/inject-nodejs: "false"
        instrumentation.opentelemetry.io/inject-python: "false"
        instrumentation.opentelemetry.io/inject-dotnet: "false"
    spec:
      containers:
        - name: backend
          image: 104469711976.dkr.ecr.us-east-1.amazonaws.com/despachos-backend:eks-v1 # Colocar uri de tu imagen en ECR
          ports:
            - containerPort: 8081
          env:
            - name: DB_ENDPOINT
              value: "innovatech-db"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: DB_NAME
              value: "innovatech_db"
            - name: DB_PORT
              value: "3306"

          # Se agrega Resource para que Metrics Server calcule el % de CPU y Memoria para escalar 
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # HEALTH CHECKS (PROBES)
          # readinessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 8081
          #   initialDelaySeconds: 5
          #   periodSeconds: 5

          # livenessProbe:
          #   httpGet:
          #     path: /api/health
          #     port: 8081
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
