apiVersion: v1
kind: Service
metadata:
  name: innovatech-db
  namespace: innovatech-chile
spec:
  selector:
    app: innovatech-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
